apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-frontend-application
  namespace: ecommerce
spec:
  project: default
  source:
    repoURL: https://github.com/lebataii/ecommerce.git
    targetRevision: HEAD
    path: argocd/app/config
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
